### ISSUE TITLE
[BUG] Воспроизводимость пайплайна DVC

### ISSUE THREAD

**Issue by stllfe** [stllfe/yoric#13]
### Проблема
Сейчас в пайплайне DVC на первом шаге загрузки данных из Википедии у неё не зафиксирована дата (latest).
Таким образом, при перезапуске загрузки мы каждый раз будем получать разную версию данных.
Это не круто пока мы в стадии экспериментов (потом можно будет сделать обновление по графику), поэтому надо зафиксировать версию какой-либо текущей датой.

Как следствие этой же проблемы, я не могу указать скрипт загрузки в качестве зависимости этого стейджа. Из-за этого в свою очередь, поскольку у стейджа нет зависимостей, которые можно было бы быстро проверить, DVC каждый раз при любом действии высчитывает хэш от всего датасета.

### TODO
- [x] Зафиксировать дату дампа Википедии в скрипте загрузки
- [x] Указать в качестве зависимости у стейджа `download-ruwiki` сам скрипт загрузки
- [x] Пересчитать весь пайплайн и обновить артефакты в репозитории
